version: '3.1'

services:

 wordpress:
   image: apache-phpmyadmin 
   links:
     - mysql
   restart: always
   container_name: apache 
   ports:
    - "8080:80"
   volumes:
     - apache_log_volume:/usr/local/apache/logs

 mysql:
   image: dagman62/mysql:5.7
   restart: always
   container_name: mysql
   environment:
     MYSQL_ROOT_PASSWORD: "example"

volumes:
  apache_log_volume:
